### PR TITLE
change file/folder names

### PR DESCRIPTION
**Pull request by danewalton**

### CODE REVIEW

**Comment by danewalton** [comment]
> project(azure_ulib_c)

this should probably be changed

---
Refers to: CMakeLists.txt:6 in 636efb8. [](commit_id = 636efb8709b894382148928ca2f8415670a19ca6, deletion_comment = True)

**Comment by danewalton** [comment]
> project(azure_ulib_c)

on second thought no because this is the name of the repo

---
In reply to: [547048726](https://github.com/Azure/azure-ulib-c/pull/44#issuecomment-547048726) [](ancestors = 547048726)

---
Refers to: CMakeLists.txt:6 in 636efb8. [](commit_id = 636efb8709b894382148928ca2f8415670a19ca6, deletion_comment = True)

**Comment by mamokarz** [comment]
> #ifndef USTREAM_CTEST_AUX_H

Consider rename all these test files from ustream_... to az_ulib_...

---
Refers to: tests/inc/ustream_ctest_aux.h:4 in ed08ae5. [](commit_id = ed08ae5799d238f6444176177037aa2084dc281e, deletion_comment = False)

**Comment by mamokarz** [comment]
> // Copyright (c) Microsoft. All rights reserved.

Please add az_ulib_ on the files for the tests as well.

---
Refers to: tests/tests_e2e/az_ulib_ustream_e2e/ustream_e2e.c:1 in ed08ae5. [](commit_id = ed08ae5799d238f6444176177037aa2084dc281e, deletion_comment = False)

**Pull request merged**
