### PR TITLE
customize doc scripts for ulib

### PR DESCRIPTION
**Pull request by smcd253**

### CODE REVIEW

**Comment by danewalton** [comment]
Sneaking in here for a pro tip. You can add a file to the index as executable and won't have to do it in the build script.

```bash
git update-index --chmod=+x .github/scripts/doxygen.sh
```

**Comment by smcd253** [comment]
notes:
* must run ssh-keygen without passphrase for deploy key to work
* run `doxygen Doxyfile` _inside_ `/docs` to overwrite current documentation
* publish from gh-pages /root

**Comment by smcd253** [comment]
notes:
* run action from from branch with full commit hash

**Review by mamokarz — APPROVED** [review]
:shipit:

**Pull request merged**
