### PR TITLE
Remove az_ulib_ulog

### PR DESCRIPTION
**Pull request by smcd253**
Logging will be handled by az_log from now on

### CODE REVIEW

**Review by cindydeng1998 — APPROVED** [review]
👍

**Comment by mamokarz** [comment]
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

Let's regenerate the entire documentation at the end of the cleanup. For now, let's just make sure that the documentation in the code is correct.

---
Refers to: docs/index.html:1 in 701e680. [](commit_id = 701e680ce416189ae749969e97870bb319e7f41a, deletion_comment = False)

**Comment by mamokarz** [comment]
> * [**uLog**](https://azure.github.io/azure-ulib-c/ulog_8h.html): a small logging system with constant strings for reduced memory footprint.

Please remove.

---
Refers to: README.md:12 in 701e680. [](commit_id = 701e680ce416189ae749969e97870bb319e7f41a, deletion_comment = False)

**Review by mamokarz — APPROVED** [review]
:shipit:

**Pull request merged**
