### PR TITLE
Rename action to capability to follow DTDL naming.

### PR DESCRIPTION
**Pull request by mamokarz**

### CODE REVIEW

**Review by smcd253 — APPROVED** [review]
looks good to me!

**Review by danewalton — APPROVED** [review]
Just out of curiousity, why not command?

**Comment by mamokarz** [comment]
Thanks

---
In reply to: [571418261](https://github.com/Azure/azure-ulib-c/pull/54#issuecomment-571418261) [](ancestors = 571418261)

**Comment by mamokarz** [comment]
Next PR I'll fix the capability names, Including Command.

---
In reply to: [571426682](https://github.com/Azure/azure-ulib-c/pull/54#issuecomment-571426682) [](ancestors = 571426682)

**Pull request merged**
